[package]
name = "pg_query"
description = "PostgreSQL parser that uses the actual PostgreSQL server source to parse SQL queries and return the internal PostgreSQL parse tree."
version = "0.1.1"
authors = ["Paul Mason <paul@form1.co.nz>"]
edition = "2018"
documentation = "https://docs.rs/pg_query/"
build = "build.rs"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/paupino/pg_query"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.9.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0.30"

[build-dependencies]
bindgen = "0.58"
clippy = { version = "0", optional = true }
prost-build = "0.9.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
